void ff_frame_thread_encoder_free() {}
void ff_frame_thread_encoder_init() {}
void ff_thread_flush() {}
void ff_thread_decode_frame() {}
void ff_thread_free() {}
void ff_thread_video_encode_frame() {}
void ff_print_debug_info2() {}
void ff_vdpau_h264_picture_start() {}
void ff_vdpau_add_data_chunk() {}
void ff_me_cmp_init_arm() {}
void ff_me_cmp_init_alpha() {}
void ff_me_cmp_init_mips() {}
void ff_me_cmp_init_ppc() {}
void ff_vdpau_h264_picture_complete() {}
void ff_vdpau_h264_set_reference_frames() {}
void ff_h264chroma_init_mips() {}
void ff_h264chroma_init_aarch64() {}
void ff_h264chroma_init_ppc() {}
void ff_h264chroma_init_arm() {}
void ff_h264dsp_init_mips() {}
void ff_h264dsp_init_aarch64() {}
void ff_h264dsp_init_ppc() {}
void ff_h264dsp_init_arm() {}
void ff_videodsp_init_ppc() {}
void ff_videodsp_init_arm() {}
void ff_videodsp_init_aarch64() {}
void ff_h264qpel_init_aarch64() {}
void ff_h264qpel_init_mips() {}
void ff_h264qpel_init_ppc() {}
void ff_h264qpel_init_arm() {}
void ff_h264_pred_init_mips() {}
void ff_h264_pred_init_arm() {}
void ff_h264_pred_init_aarch64() {}
void ff_get_cpu_flags_arm() {}
void ff_get_cpu_flags_aarch64() {}
void ff_get_cpu_flags_ppc() {}
void ff_sws_init_swscale_ppc() {}
void ff_sws_init_swscale_aarch64() {}
void ff_sws_init_swscale_arm() {}
void ff_yuv2rgb_init_tables_ppc() {}
void ff_yuv2rgb_init_ppc() {}
void ff_get_unscaled_swscale_ppc() {}
void ff_get_unscaled_swscale_arm() {}
void ff_get_unscaled_swscale_aarch64() {}
