void ff_frame_thread_encoder_free() {}
void ff_frame_thread_encoder_init() {}
void ff_get_cpu_flags_aarch64() {}
void ff_get_cpu_flags_arm() {}
void ff_get_cpu_flags_ppc() {}
void ff_get_cpu_max_align_aarch64() {}
void ff_get_cpu_max_align_arm() {}
void ff_get_cpu_max_align_ppc() {}
void ff_get_unscaled_swscale_aarch64() {}
void ff_get_unscaled_swscale_arm() {}
void ff_get_unscaled_swscale_ppc() {}
void ff_h264_pred_init_aarch64() {}
void ff_h264_pred_init_arm() {}
void ff_h264_pred_init_mips() {}
void ff_h264chroma_init_aarch64() {}
void ff_h264chroma_init_arm() {}
void ff_h264chroma_init_mips() {}
void ff_h264chroma_init_ppc() {}
void ff_h264dsp_init_aarch64() {}
void ff_h264dsp_init_arm() {}
void ff_h264dsp_init_mips() {}
void ff_h264dsp_init_ppc() {}
void ff_h264qpel_init_aarch64() {}
void ff_h264qpel_init_arm() {}
void ff_h264qpel_init_mips() {}
void ff_h264qpel_init_ppc() {}
void ff_hevc_dsp_init_arm() {}
void ff_hevc_dsp_init_mips() {}
void ff_hevc_pred_init_mips() {}
void ff_hevcdsp_init_arm() {}
void ff_me_cmp_init_alpha() {}
void ff_me_cmp_init_arm() {}
void ff_me_cmp_init_mips() {}
void ff_me_cmp_init_ppc() {}
void ff_print_debug_info2() {}
void ff_sws_init_swscale_aarch64() {}
void ff_sws_init_swscale_arm() {}
void ff_sws_init_swscale_ppc() {}
void ff_thread_decode_frame() {}
void ff_thread_flush() {}
void ff_thread_free() {}
void ff_thread_video_encode_frame() {}
void ff_vdpau_add_data_chunk() {}
void ff_vdpau_h264_picture_complete() {}
void ff_vdpau_h264_picture_start() {}
void ff_vdpau_h264_set_reference_frames() {}
void ff_videodsp_init_aarch64() {}
void ff_videodsp_init_arm() {}
void ff_videodsp_init_mips() {}
void ff_videodsp_init_ppc() {}
void ff_yuv2rgb_init_ppc() {}
void ff_yuv2rgb_init_tables_ppc() {}

void ff_hevc_dsp_init_ppc() {}
void ff_get_cpu_flags_mips() {}
void ff_get_cpu_max_align_mips() {}
void rgb2rgb_init_aarch64() {}

#ifndef _WIN64

void ff_hevc_h_loop_filter_luma_10_avx() {}
void ff_hevc_h_loop_filter_luma_10_sse2() {}
void ff_hevc_h_loop_filter_luma_10_ssse3() {}
void ff_hevc_h_loop_filter_luma_12_avx() {}
void ff_hevc_h_loop_filter_luma_12_sse2() {}
void ff_hevc_h_loop_filter_luma_12_ssse3() {}
void ff_hevc_h_loop_filter_luma_8_avx() {}
void ff_hevc_h_loop_filter_luma_8_sse2() {}
void ff_hevc_h_loop_filter_luma_8_ssse3() {}
void ff_hevc_idct_16x16_10_avx() {}
void ff_hevc_idct_16x16_10_sse2() {}
void ff_hevc_idct_16x16_8_avx() {}
void ff_hevc_idct_16x16_8_sse2() {}
void ff_hevc_idct_32x32_10_avx() {}
void ff_hevc_idct_32x32_10_sse2() {}
void ff_hevc_idct_32x32_8_avx() {}
void ff_hevc_idct_32x32_8_sse2() {}
void ff_hevc_put_hevc_bi_epel_h12_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h12_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h12_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h16_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_h16_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h16_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h16_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h24_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_h24_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h24_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h24_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h32_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_h32_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h32_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h32_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_h32_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h4_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h4_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h4_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h48_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_h48_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h48_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h48_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_h48_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h6_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h6_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h6_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h64_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_h64_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h64_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h64_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_h64_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_h8_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_h8_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_h8_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv12_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv12_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv12_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv16_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv16_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv16_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv16_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv24_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv24_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv24_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv24_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv32_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv32_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv32_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv32_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv32_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv4_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv4_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv4_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv48_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv48_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv48_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv48_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv48_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv6_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv6_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv6_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv64_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv64_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv64_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv64_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_hv64_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv8_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv8_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_hv8_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v12_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v12_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v12_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v16_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_v16_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v16_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v16_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v24_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_v24_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v24_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v24_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v32_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_v32_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v32_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v32_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_v32_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v4_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v4_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v4_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v48_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_v48_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v48_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v48_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_v48_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v6_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v6_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v6_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v64_10_avx2() {}
void ff_hevc_put_hevc_bi_epel_v64_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v64_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v64_8_avx2() {}
void ff_hevc_put_hevc_bi_epel_v64_8_sse4() {}
void ff_hevc_put_hevc_bi_epel_v8_10_sse4() {}
void ff_hevc_put_hevc_bi_epel_v8_12_sse4() {}
void ff_hevc_put_hevc_bi_epel_v8_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels12_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels12_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels12_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels16_10_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels16_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels16_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels16_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels24_10_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels24_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels24_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels24_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels32_10_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels32_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels32_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels32_8_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels32_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels4_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels4_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels4_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels48_10_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels48_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels48_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels48_8_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels48_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels6_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels6_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels6_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels64_10_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels64_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels64_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels64_8_avx2() {}
void ff_hevc_put_hevc_bi_pel_pixels64_8_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels8_10_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels8_12_sse4() {}
void ff_hevc_put_hevc_bi_pel_pixels8_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h12_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h12_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h12_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h16_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h16_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h16_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h16_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h24_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h24_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h24_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h24_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h32_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h32_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h32_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h32_8_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h32_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h4_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h4_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h4_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h48_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h48_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h48_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h48_8_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h48_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h64_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h64_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h64_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h64_8_avx2() {}
void ff_hevc_put_hevc_bi_qpel_h64_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h8_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h8_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_h8_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv12_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv12_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv12_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv16_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_hv16_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv16_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv16_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv24_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_hv24_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv24_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv24_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv32_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_hv32_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv32_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv32_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv4_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv4_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv4_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv48_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_hv48_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv48_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv48_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv64_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_hv64_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv64_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv64_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv8_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv8_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_hv8_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v12_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v12_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v12_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v16_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v16_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v16_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v16_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v24_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v24_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v24_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v24_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v32_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v32_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v32_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v32_8_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v32_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v4_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v4_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v4_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v48_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v48_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v48_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v48_8_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v48_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v64_10_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v64_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v64_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v64_8_avx2() {}
void ff_hevc_put_hevc_bi_qpel_v64_8_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v8_10_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v8_12_sse4() {}
void ff_hevc_put_hevc_bi_qpel_v8_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h12_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h12_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h12_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h16_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h16_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h16_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h24_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h24_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h24_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h32_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h32_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h32_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h4_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h4_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h4_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h48_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h48_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h48_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h6_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h6_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h6_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h64_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h64_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h64_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h8_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h8_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_h8_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv12_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv12_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv12_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv16_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv16_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv16_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv24_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv24_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv24_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv32_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv32_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv32_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv4_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv4_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv4_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv48_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv48_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv48_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv6_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv6_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv6_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv64_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv64_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv64_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv8_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv8_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_hv8_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v12_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v12_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v12_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v16_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v16_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v16_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v24_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v24_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v24_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v32_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v32_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v32_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v4_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v4_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v4_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v48_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v48_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v48_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v6_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v6_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v6_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v64_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v64_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v64_8_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v8_10_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v8_12_sse4() {}
void ff_hevc_put_hevc_bi_w_epel_v8_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels12_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels12_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels12_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels16_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels16_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels16_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels24_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels24_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels24_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels32_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels32_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels32_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels4_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels4_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels4_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels48_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels48_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels48_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels6_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels6_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels6_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels64_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels64_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels64_8_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels8_10_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels8_12_sse4() {}
void ff_hevc_put_hevc_bi_w_pel_pixels8_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h12_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h12_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h12_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h16_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h16_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h16_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h24_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h24_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h24_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h32_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h32_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h32_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h4_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h4_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h4_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h48_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h48_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h48_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h64_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h64_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h64_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h8_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h8_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_h8_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv12_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv12_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv12_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv16_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv16_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv16_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv24_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv24_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv24_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv32_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv32_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv32_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv4_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv4_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv4_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv48_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv48_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv48_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv64_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv64_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv64_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv8_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv8_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_hv8_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v12_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v12_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v12_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v16_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v16_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v16_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v24_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v24_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v24_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v32_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v32_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v32_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v4_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v4_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v4_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v48_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v48_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v48_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v64_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v64_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v64_8_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v8_10_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v8_12_sse4() {}
void ff_hevc_put_hevc_bi_w_qpel_v8_8_sse4() {}
void ff_hevc_put_hevc_epel_h12_10_sse4() {}
void ff_hevc_put_hevc_epel_h12_12_sse4() {}
void ff_hevc_put_hevc_epel_h12_8_sse4() {}
void ff_hevc_put_hevc_epel_h16_10_avx2() {}
void ff_hevc_put_hevc_epel_h16_10_sse4() {}
void ff_hevc_put_hevc_epel_h16_12_sse4() {}
void ff_hevc_put_hevc_epel_h16_8_sse4() {}
void ff_hevc_put_hevc_epel_h24_10_avx2() {}
void ff_hevc_put_hevc_epel_h24_10_sse4() {}
void ff_hevc_put_hevc_epel_h24_12_sse4() {}
void ff_hevc_put_hevc_epel_h24_8_sse4() {}
void ff_hevc_put_hevc_epel_h32_10_avx2() {}
void ff_hevc_put_hevc_epel_h32_10_sse4() {}
void ff_hevc_put_hevc_epel_h32_12_sse4() {}
void ff_hevc_put_hevc_epel_h32_8_avx2() {}
void ff_hevc_put_hevc_epel_h32_8_sse4() {}
void ff_hevc_put_hevc_epel_h4_10_sse4() {}
void ff_hevc_put_hevc_epel_h4_12_sse4() {}
void ff_hevc_put_hevc_epel_h4_8_sse4() {}
void ff_hevc_put_hevc_epel_h48_10_avx2() {}
void ff_hevc_put_hevc_epel_h48_10_sse4() {}
void ff_hevc_put_hevc_epel_h48_12_sse4() {}
void ff_hevc_put_hevc_epel_h48_8_avx2() {}
void ff_hevc_put_hevc_epel_h48_8_sse4() {}
void ff_hevc_put_hevc_epel_h6_10_sse4() {}
void ff_hevc_put_hevc_epel_h6_12_sse4() {}
void ff_hevc_put_hevc_epel_h6_8_sse4() {}
void ff_hevc_put_hevc_epel_h64_10_avx2() {}
void ff_hevc_put_hevc_epel_h64_10_sse4() {}
void ff_hevc_put_hevc_epel_h64_12_sse4() {}
void ff_hevc_put_hevc_epel_h64_8_avx2() {}
void ff_hevc_put_hevc_epel_h64_8_sse4() {}
void ff_hevc_put_hevc_epel_h8_10_sse4() {}
void ff_hevc_put_hevc_epel_h8_12_sse4() {}
void ff_hevc_put_hevc_epel_h8_8_sse4() {}
void ff_hevc_put_hevc_epel_hv12_10_sse4() {}
void ff_hevc_put_hevc_epel_hv12_12_sse4() {}
void ff_hevc_put_hevc_epel_hv12_8_sse4() {}
void ff_hevc_put_hevc_epel_hv16_10_avx2() {}
void ff_hevc_put_hevc_epel_hv16_10_sse4() {}
void ff_hevc_put_hevc_epel_hv16_12_sse4() {}
void ff_hevc_put_hevc_epel_hv16_8_sse4() {}
void ff_hevc_put_hevc_epel_hv24_10_avx2() {}
void ff_hevc_put_hevc_epel_hv24_10_sse4() {}
void ff_hevc_put_hevc_epel_hv24_12_sse4() {}
void ff_hevc_put_hevc_epel_hv24_8_sse4() {}
void ff_hevc_put_hevc_epel_hv32_10_avx2() {}
void ff_hevc_put_hevc_epel_hv32_10_sse4() {}
void ff_hevc_put_hevc_epel_hv32_12_sse4() {}
void ff_hevc_put_hevc_epel_hv32_8_avx2() {}
void ff_hevc_put_hevc_epel_hv32_8_sse4() {}
void ff_hevc_put_hevc_epel_hv4_10_sse4() {}
void ff_hevc_put_hevc_epel_hv4_12_sse4() {}
void ff_hevc_put_hevc_epel_hv4_8_sse4() {}
void ff_hevc_put_hevc_epel_hv48_10_avx2() {}
void ff_hevc_put_hevc_epel_hv48_10_sse4() {}
void ff_hevc_put_hevc_epel_hv48_12_sse4() {}
void ff_hevc_put_hevc_epel_hv48_8_avx2() {}
void ff_hevc_put_hevc_epel_hv48_8_sse4() {}
void ff_hevc_put_hevc_epel_hv6_10_sse4() {}
void ff_hevc_put_hevc_epel_hv6_12_sse4() {}
void ff_hevc_put_hevc_epel_hv6_8_sse4() {}
void ff_hevc_put_hevc_epel_hv64_10_avx2() {}
void ff_hevc_put_hevc_epel_hv64_10_sse4() {}
void ff_hevc_put_hevc_epel_hv64_12_sse4() {}
void ff_hevc_put_hevc_epel_hv64_8_avx2() {}
void ff_hevc_put_hevc_epel_hv64_8_sse4() {}
void ff_hevc_put_hevc_epel_hv8_10_sse4() {}
void ff_hevc_put_hevc_epel_hv8_12_sse4() {}
void ff_hevc_put_hevc_epel_hv8_8_sse4() {}
void ff_hevc_put_hevc_epel_v12_10_sse4() {}
void ff_hevc_put_hevc_epel_v12_12_sse4() {}
void ff_hevc_put_hevc_epel_v12_8_sse4() {}
void ff_hevc_put_hevc_epel_v16_10_avx2() {}
void ff_hevc_put_hevc_epel_v16_10_sse4() {}
void ff_hevc_put_hevc_epel_v16_12_sse4() {}
void ff_hevc_put_hevc_epel_v16_8_sse4() {}
void ff_hevc_put_hevc_epel_v24_10_avx2() {}
void ff_hevc_put_hevc_epel_v24_10_sse4() {}
void ff_hevc_put_hevc_epel_v24_12_sse4() {}
void ff_hevc_put_hevc_epel_v24_8_sse4() {}
void ff_hevc_put_hevc_epel_v32_10_avx2() {}
void ff_hevc_put_hevc_epel_v32_10_sse4() {}
void ff_hevc_put_hevc_epel_v32_12_sse4() {}
void ff_hevc_put_hevc_epel_v32_8_avx2() {}
void ff_hevc_put_hevc_epel_v32_8_sse4() {}
void ff_hevc_put_hevc_epel_v4_10_sse4() {}
void ff_hevc_put_hevc_epel_v4_12_sse4() {}
void ff_hevc_put_hevc_epel_v4_8_sse4() {}
void ff_hevc_put_hevc_epel_v48_10_avx2() {}
void ff_hevc_put_hevc_epel_v48_10_sse4() {}
void ff_hevc_put_hevc_epel_v48_12_sse4() {}
void ff_hevc_put_hevc_epel_v48_8_avx2() {}
void ff_hevc_put_hevc_epel_v48_8_sse4() {}
void ff_hevc_put_hevc_epel_v6_10_sse4() {}
void ff_hevc_put_hevc_epel_v6_12_sse4() {}
void ff_hevc_put_hevc_epel_v6_8_sse4() {}
void ff_hevc_put_hevc_epel_v64_10_avx2() {}
void ff_hevc_put_hevc_epel_v64_10_sse4() {}
void ff_hevc_put_hevc_epel_v64_12_sse4() {}
void ff_hevc_put_hevc_epel_v64_8_avx2() {}
void ff_hevc_put_hevc_epel_v64_8_sse4() {}
void ff_hevc_put_hevc_epel_v8_10_sse4() {}
void ff_hevc_put_hevc_epel_v8_12_sse4() {}
void ff_hevc_put_hevc_epel_v8_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels12_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels12_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels12_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels16_10_avx2() {}
void ff_hevc_put_hevc_pel_pixels16_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels16_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels16_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels24_10_avx2() {}
void ff_hevc_put_hevc_pel_pixels24_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels24_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels24_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels32_10_avx2() {}
void ff_hevc_put_hevc_pel_pixels32_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels32_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels32_8_avx2() {}
void ff_hevc_put_hevc_pel_pixels32_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels4_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels4_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels4_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels48_10_avx2() {}
void ff_hevc_put_hevc_pel_pixels48_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels48_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels48_8_avx2() {}
void ff_hevc_put_hevc_pel_pixels48_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels6_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels6_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels6_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels64_10_avx2() {}
void ff_hevc_put_hevc_pel_pixels64_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels64_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels64_8_avx2() {}
void ff_hevc_put_hevc_pel_pixels64_8_sse4() {}
void ff_hevc_put_hevc_pel_pixels8_10_sse4() {}
void ff_hevc_put_hevc_pel_pixels8_12_sse4() {}
void ff_hevc_put_hevc_pel_pixels8_8_sse4() {}
void ff_hevc_put_hevc_qpel_h12_10_sse4() {}
void ff_hevc_put_hevc_qpel_h12_12_sse4() {}
void ff_hevc_put_hevc_qpel_h12_8_sse4() {}
void ff_hevc_put_hevc_qpel_h16_10_avx2() {}
void ff_hevc_put_hevc_qpel_h16_10_sse4() {}
void ff_hevc_put_hevc_qpel_h16_12_sse4() {}
void ff_hevc_put_hevc_qpel_h16_8_sse4() {}
void ff_hevc_put_hevc_qpel_h24_10_avx2() {}
void ff_hevc_put_hevc_qpel_h24_10_sse4() {}
void ff_hevc_put_hevc_qpel_h24_12_sse4() {}
void ff_hevc_put_hevc_qpel_h24_8_sse4() {}
void ff_hevc_put_hevc_qpel_h32_10_avx2() {}
void ff_hevc_put_hevc_qpel_h32_10_sse4() {}
void ff_hevc_put_hevc_qpel_h32_12_sse4() {}
void ff_hevc_put_hevc_qpel_h32_8_avx2() {}
void ff_hevc_put_hevc_qpel_h32_8_sse4() {}
void ff_hevc_put_hevc_qpel_h4_10_sse4() {}
void ff_hevc_put_hevc_qpel_h4_12_sse4() {}
void ff_hevc_put_hevc_qpel_h4_8_sse4() {}
void ff_hevc_put_hevc_qpel_h48_10_avx2() {}
void ff_hevc_put_hevc_qpel_h48_10_sse4() {}
void ff_hevc_put_hevc_qpel_h48_12_sse4() {}
void ff_hevc_put_hevc_qpel_h48_8_avx2() {}
void ff_hevc_put_hevc_qpel_h48_8_sse4() {}
void ff_hevc_put_hevc_qpel_h64_10_avx2() {}
void ff_hevc_put_hevc_qpel_h64_10_sse4() {}
void ff_hevc_put_hevc_qpel_h64_12_sse4() {}
void ff_hevc_put_hevc_qpel_h64_8_avx2() {}
void ff_hevc_put_hevc_qpel_h64_8_sse4() {}
void ff_hevc_put_hevc_qpel_h8_10_sse4() {}
void ff_hevc_put_hevc_qpel_h8_12_sse4() {}
void ff_hevc_put_hevc_qpel_h8_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv12_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv12_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv12_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv16_10_avx2() {}
void ff_hevc_put_hevc_qpel_hv16_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv16_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv16_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv24_10_avx2() {}
void ff_hevc_put_hevc_qpel_hv24_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv24_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv24_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv32_10_avx2() {}
void ff_hevc_put_hevc_qpel_hv32_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv32_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv32_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv4_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv4_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv4_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv48_10_avx2() {}
void ff_hevc_put_hevc_qpel_hv48_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv48_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv48_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv64_10_avx2() {}
void ff_hevc_put_hevc_qpel_hv64_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv64_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv64_8_sse4() {}
void ff_hevc_put_hevc_qpel_hv8_10_sse4() {}
void ff_hevc_put_hevc_qpel_hv8_12_sse4() {}
void ff_hevc_put_hevc_qpel_hv8_8_sse4() {}
void ff_hevc_put_hevc_qpel_v12_10_sse4() {}
void ff_hevc_put_hevc_qpel_v12_12_sse4() {}
void ff_hevc_put_hevc_qpel_v12_8_sse4() {}
void ff_hevc_put_hevc_qpel_v16_10_avx2() {}
void ff_hevc_put_hevc_qpel_v16_10_sse4() {}
void ff_hevc_put_hevc_qpel_v16_12_sse4() {}
void ff_hevc_put_hevc_qpel_v16_8_sse4() {}
void ff_hevc_put_hevc_qpel_v24_10_avx2() {}
void ff_hevc_put_hevc_qpel_v24_10_sse4() {}
void ff_hevc_put_hevc_qpel_v24_12_sse4() {}
void ff_hevc_put_hevc_qpel_v24_8_sse4() {}
void ff_hevc_put_hevc_qpel_v32_10_avx2() {}
void ff_hevc_put_hevc_qpel_v32_10_sse4() {}
void ff_hevc_put_hevc_qpel_v32_12_sse4() {}
void ff_hevc_put_hevc_qpel_v32_8_avx2() {}
void ff_hevc_put_hevc_qpel_v32_8_sse4() {}
void ff_hevc_put_hevc_qpel_v4_10_sse4() {}
void ff_hevc_put_hevc_qpel_v4_12_sse4() {}
void ff_hevc_put_hevc_qpel_v4_8_sse4() {}
void ff_hevc_put_hevc_qpel_v48_10_avx2() {}
void ff_hevc_put_hevc_qpel_v48_10_sse4() {}
void ff_hevc_put_hevc_qpel_v48_12_sse4() {}
void ff_hevc_put_hevc_qpel_v48_8_avx2() {}
void ff_hevc_put_hevc_qpel_v48_8_sse4() {}
void ff_hevc_put_hevc_qpel_v64_10_avx2() {}
void ff_hevc_put_hevc_qpel_v64_10_sse4() {}
void ff_hevc_put_hevc_qpel_v64_12_sse4() {}
void ff_hevc_put_hevc_qpel_v64_8_avx2() {}
void ff_hevc_put_hevc_qpel_v64_8_sse4() {}
void ff_hevc_put_hevc_qpel_v8_10_sse4() {}
void ff_hevc_put_hevc_qpel_v8_12_sse4() {}
void ff_hevc_put_hevc_qpel_v8_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h12_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h12_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h12_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h16_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_h16_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h16_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h16_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h24_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_h24_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h24_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h24_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h32_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_h32_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h32_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h32_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_h32_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h4_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h4_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h4_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h48_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_h48_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h48_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h48_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_h48_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h6_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h6_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h6_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h64_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_h64_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h64_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h64_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_h64_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_h8_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_h8_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_h8_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv12_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv12_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv12_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv16_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv16_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv16_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv16_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv24_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv24_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv24_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv24_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv32_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv32_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv32_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv32_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv32_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv4_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv4_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv4_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv48_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv48_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv48_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv48_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv48_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv6_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv6_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv6_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv64_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv64_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv64_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv64_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_hv64_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv8_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv8_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_hv8_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v12_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v12_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v12_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v16_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_v16_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v16_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v16_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v24_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_v24_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v24_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v24_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v32_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_v32_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v32_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v32_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_v32_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v4_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v4_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v4_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v48_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_v48_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v48_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v48_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_v48_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v6_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v6_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v6_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v64_10_avx2() {}
void ff_hevc_put_hevc_uni_epel_v64_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v64_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v64_8_avx2() {}
void ff_hevc_put_hevc_uni_epel_v64_8_sse4() {}
void ff_hevc_put_hevc_uni_epel_v8_10_sse4() {}
void ff_hevc_put_hevc_uni_epel_v8_12_sse4() {}
void ff_hevc_put_hevc_uni_epel_v8_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels12_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels12_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels12_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels128_8_avx2() {}
void ff_hevc_put_hevc_uni_pel_pixels16_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels16_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels16_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels24_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels24_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels24_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels32_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels32_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels32_8_avx2() {}
void ff_hevc_put_hevc_uni_pel_pixels32_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels4_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels4_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels4_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels48_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels48_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels48_8_avx2() {}
void ff_hevc_put_hevc_uni_pel_pixels48_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels6_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels6_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels6_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels64_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels64_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels64_8_avx2() {}
void ff_hevc_put_hevc_uni_pel_pixels64_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels8_10_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels8_12_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels8_8_sse4() {}
void ff_hevc_put_hevc_uni_pel_pixels96_8_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h12_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h12_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h12_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h16_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h16_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h16_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h16_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h24_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h24_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h24_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h24_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h32_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h32_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h32_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h32_8_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h32_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h4_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h4_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h4_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h48_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h48_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h48_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h48_8_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h48_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h64_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h64_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h64_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h64_8_avx2() {}
void ff_hevc_put_hevc_uni_qpel_h64_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h8_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h8_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_h8_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv12_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv12_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv12_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv16_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_hv16_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv16_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv16_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv24_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_hv24_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv24_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv24_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv32_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_hv32_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv32_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv32_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv4_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv4_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv4_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv48_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_hv48_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv48_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv48_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv64_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_hv64_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv64_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv64_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv8_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv8_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_hv8_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v12_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v12_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v12_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v16_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v16_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v16_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v16_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v24_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v24_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v24_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v24_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v32_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v32_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v32_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v32_8_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v32_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v4_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v4_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v4_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v48_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v48_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v48_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v48_8_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v48_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v64_10_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v64_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v64_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v64_8_avx2() {}
void ff_hevc_put_hevc_uni_qpel_v64_8_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v8_10_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v8_12_sse4() {}
void ff_hevc_put_hevc_uni_qpel_v8_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h12_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h12_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h12_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h16_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h16_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h16_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h24_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h24_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h24_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h32_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h32_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h32_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h4_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h4_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h4_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h48_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h48_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h48_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h6_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h6_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h6_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h64_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h64_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h64_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h8_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h8_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_h8_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv12_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv12_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv12_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv16_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv16_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv16_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv24_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv24_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv24_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv32_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv32_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv32_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv4_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv4_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv4_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv48_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv48_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv48_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv6_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv6_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv6_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv64_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv64_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv64_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv8_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv8_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_hv8_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v12_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v12_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v12_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v16_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v16_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v16_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v24_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v24_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v24_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v32_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v32_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v32_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v4_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v4_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v4_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v48_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v48_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v48_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v6_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v6_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v6_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v64_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v64_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v64_8_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v8_10_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v8_12_sse4() {}
void ff_hevc_put_hevc_uni_w_epel_v8_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels12_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels12_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels12_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels16_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels16_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels16_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels24_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels24_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels24_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels32_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels32_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels32_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels4_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels4_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels4_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels48_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels48_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels48_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels6_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels6_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels6_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels64_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels64_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels64_8_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels8_10_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels8_12_sse4() {}
void ff_hevc_put_hevc_uni_w_pel_pixels8_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h12_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h12_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h12_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h16_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h16_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h16_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h24_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h24_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h24_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h32_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h32_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h32_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h4_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h4_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h4_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h48_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h48_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h48_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h64_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h64_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h64_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h8_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h8_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_h8_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv12_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv12_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv12_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv16_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv16_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv16_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv24_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv24_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv24_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv32_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv32_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv32_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv4_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv4_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv4_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv48_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv48_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv48_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv64_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv64_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv64_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv8_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv8_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_hv8_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v12_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v12_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v12_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v16_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v16_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v16_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v24_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v24_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v24_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v32_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v32_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v32_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v4_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v4_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v4_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v48_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v48_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v48_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v64_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v64_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v64_8_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v8_10_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v8_12_sse4() {}
void ff_hevc_put_hevc_uni_w_qpel_v8_8_sse4() {}
void ff_hevc_v_loop_filter_luma_10_avx() {}
void ff_hevc_v_loop_filter_luma_10_sse2() {}
void ff_hevc_v_loop_filter_luma_10_ssse3() {}
void ff_hevc_v_loop_filter_luma_12_avx() {}
void ff_hevc_v_loop_filter_luma_12_sse2() {}
void ff_hevc_v_loop_filter_luma_12_ssse3() {}
void ff_hevc_v_loop_filter_luma_8_avx() {}
void ff_hevc_v_loop_filter_luma_8_sse2() {}
void ff_hevc_v_loop_filter_luma_8_ssse3() {}

#endif
